blueprint:
  name: Play latest episode of a podcast on Spotify
  domain: script
  author: Home Automation Lab
  input:
    entity_id:
      name: Spotify Entity
      selector:
        entity:
          filter:
            integration: spotify
    podcast_id:
      name: Spotify Podcast
      description: Podcast show URL (from Share menu)
      selector:
        text:
          type: url
    
sequence:
  - action: media_player.play_media
    data:
      media_content_type: show
      media_content_id: !input podcast_id
    target:
      entity_id: !input entity_id
