blueprint:
  name: Play latest episode of a podcast on Spotify
  domain: script
  author: Home Automation Lab
  input:
    entity_id:
      name: Spotify Entity
      icon: mdi:spotify
      selector:
        entity:
          filter:
            integration: spotify
      required: true
    podcast_id:
      name: Spotify Podcast
      icon: mdi:podcast
      description: Podcast show URL (from Share menu)
      selector:
        text:
          type: url
      required: true
    
sequence:
  - action: media_player.play_media
    data:
      media_content_type: show
      media_content_id: !input podcast_id
    target:
      entity_id: !input entity_id
