blueprint:
  name: Play latest episode of a podcast on Spotify
  domain: script
  author: Home Automation Lab
  input:
    entity_id:
      name: Spotify Entity
      selector:
        entity:
          filter:
            integration: spotify

fields:
  spotify_podcast_url:
    description: Podcast show URL (from Share menu)
    selector:
      text: null
    name: spotify_podcast_id
    required: true

sequence:
  - action: media_player.play_media
    data:
      media_content_type: playlist
      media_content_id: "{{ spotify_podcast_url }}"
    target:
      entity_id: !input entity_id
